with-expecter: true
case: underscore
unroll-variadic: False
# outpkg: mocks
# mockname: "{{.InterfaceName}}"
# filename: "{{.MockName}}.go"
# packages:
#   sigma-test/internal/controller:
#     config:
#     interfaces:
#       UserService:
