version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sigma-inventory-db-postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: sigma-inventory-db-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
