FROM golang:1.22-alpine AS sigma-inventory-backend

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .

FROM alpine:latest
WORKDIR /app

COPY --from=sigma-inventory-backend /app/main .

EXPOSE 8081

CMD ["./main"]
