version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sigma-user-db-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: sigma-db-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  aerospike:
    container_name: sigma-user-db-aerospike
    ports:
      - 3000-3002:3000-3002
    image: aerospike/aerospike-server

volumes:
  postgres_data: {}
