FROM golang:1.22-alpine AS sigma-user-backend

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .

FROM alpine:latest
WORKDIR /app

COPY --from=sigma-user-backend /app/main .

EXPOSE 8080

CMD ["./main"]
